<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>BG_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d67a05ac-cfc9-4c69-90f4-3c8dac39f4f5</testSuiteGuid>
   <testCaseLink>
      <guid>aca10966-dd74-4e42-8305-45399208bdaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SamsungURLClassifier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cee90295-0545-40c1-9805-e0bd5a4574cd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/BG_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cee90295-0545-40c1-9805-e0bd5a4574cd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Country</value>
         <variableId>f11f06b5-bf5d-435f-b35d-faaf63312670</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cee90295-0545-40c1-9805-e0bd5a4574cd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>3dd0fabd-2612-4329-92a0-2bf514cf0130</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
