<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LATIN_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>af840538-d88b-42c0-ba7c-4feb510bd07c</testSuiteGuid>
   <testCaseLink>
      <guid>ae7398a9-c685-4527-a1ee-b49b618657b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SamsungURLClassifier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>15bab054-90db-4d03-bc8c-dd37b89e5ca5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LATIN_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>15bab054-90db-4d03-bc8c-dd37b89e5ca5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Site</value>
         <variableId>f11f06b5-bf5d-435f-b35d-faaf63312670</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15bab054-90db-4d03-bc8c-dd37b89e5ca5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>3dd0fabd-2612-4329-92a0-2bf514cf0130</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
