<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MX_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>02ba1dfe-0bd4-4a0d-8ef7-8509a6d36bed</testSuiteGuid>
   <testCaseLink>
      <guid>c9538fd2-dee6-46ab-a7d9-47c0f31a125b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SamsungURLClassifier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4de58fe9-432f-430d-9b7b-9057069ce834</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MX_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4de58fe9-432f-430d-9b7b-9057069ce834</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Country</value>
         <variableId>f11f06b5-bf5d-435f-b35d-faaf63312670</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4de58fe9-432f-430d-9b7b-9057069ce834</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>3dd0fabd-2612-4329-92a0-2bf514cf0130</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
