<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UZ_RU_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fffe1377-94d3-4f1c-9b30-1a9526146f9d</testSuiteGuid>
   <testCaseLink>
      <guid>972c85b3-52c2-47a2-86b5-bf73c5e41f8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SamsungURLClassifier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7835181c-9f52-4c94-82e3-34cfa017a5e2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/UZ_RU_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7835181c-9f52-4c94-82e3-34cfa017a5e2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Site</value>
         <variableId>f11f06b5-bf5d-435f-b35d-faaf63312670</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7835181c-9f52-4c94-82e3-34cfa017a5e2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>3dd0fabd-2612-4329-92a0-2bf514cf0130</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
