<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VN_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9c37c71a-138a-4455-b2f5-1760ba9e4683</testSuiteGuid>
   <testCaseLink>
      <guid>d31bb78a-ba5f-46cb-a876-6396786af513</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SamsungURLClassifier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>564be123-dbb3-49d7-be16-97a9527ae250</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/VN_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>564be123-dbb3-49d7-be16-97a9527ae250</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Site</value>
         <variableId>f11f06b5-bf5d-435f-b35d-faaf63312670</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>564be123-dbb3-49d7-be16-97a9527ae250</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>3dd0fabd-2612-4329-92a0-2bf514cf0130</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
