<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>offer_bundle_component</name>
   <tag></tag>
   <elementGuidId>8c9b2df2-9cb9-49eb-bf5e-dde378ee5672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.bundle-builder-component</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
